# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

pool:
  name: Ashok-Self

steps:
  - task: SonarQubePrepare@5
    inputs:
      SonarQube: 'SonarQube'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'your-project-key'
      cliProjectName: 'your-project-name'
      cliSources: '.'

  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install sonar:sonar'
      options: '-X'
      javaHomeOption: 'Path'
      jdkDirectory: '/usr/lib/jvm/java-11-openjdk-amd64'
    displayName: 'Maven Build with Sonar Scan'

  - task: SonarQubePublish@5
    inputs:
      pollingTimeoutSec: '300'

